[package]
name = "implement-the-mt19937-mersenne-twister-rng"
version = "0.1.0"
authors = ["quininer kel <quininer@live.com>"]

[dependencies.implement-ctr-the-stream-cipher-mode]
path = "../18-implement-ctr-the-stream-cipher-mode"

[dependencies]
