[package]
name = "break-an-md4keyed-mac-using-length-extension"
version = "0.1.0"
authors = ["quininer kel <quininer@live.com>"]

[dependencies.implement-a-sha-1-keyed-mac]
path = "../28-implement-a-sha-1-keyed-mac"

[dependencies]
byteorder = "*"
rustc-serialize = "*"
