[package]
name = "break-repeating-key-xor"
version = "0.1.0"
authors = ["quininer <quininer@live.com>"]

[dependencies]
rustc-serialize = "*"

[dependencies.single-byte-xor-cipher]
path = "../3-single-byte-xor-cipher"

[dependencies.detect-single-character-xor]
path = "../4-detect-single-character-xor"
