[package]
name = "compression-ratio-side-channel-attacks"
version = "0.1.0"
authors = ["quininer kel <quininer@live.com>"]

[dependencies.implement-ctr-the-stream-cipher-mode]
path = "../18-implement-ctr-the-stream-cipher-mode"

[dependencies.an-ebccbc-detection-oracle]
path = "../11-an-ebccbc-detection-oracle"

[dependencies.implement-cbc-mode]
path = "../10-implement-cbc-mode"

[dependencies.implement-pkcs7-padding]
path = "../9-implement-pkcs7-padding"

[dependencies.zlib]
git = "https://github.com/rollends/rust-zlib.git"
