[package]
name = "rkm"
version = "0.1.0"
authors = ["quininer kel <quininer@live.com>"]
build = "build.rs"

[dependencies.core]
git = "https://github.com/phil-opp/nightly-libcore.git"
features = ["disable_float"]
